export const BOARD_EVENTS_FALLBACK_POLL_INTERVAL_MS = 30000;
export const BOARD_EVENTS_HEARTBEAT_MS = 15000;
export const BOARD_PRESENCE_HEARTBEAT_MS = 15000;
export const BOARD_PRESENCE_TTL_MS = 45000;
